:website:
#  :id: "http://droots.org"
  :title: "ZeroFour adapted by digitalRoots"
#  :description: "Middleman adaption of the Zerofour HTML5 template by HTML5 UP and adapted by digitalRoots"
#  :hostname: "droots.org"
#  :domain: "droots.org"
#  :root_url: "http://droots.org"
